# PG

development:
  adapter: postgresql
  database: a7a_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: a7a_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: a7a_prod
  pool: 5
  timeout: 5000
